# Generated by Django 5.2.12 on 2026-03-17 23:52

import django.db.models.deletion
import netfields.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the ARP entry.', protocol='IPv4')),
                ('mac_address', models.CharField(help_text='MAC address in EOS dot-notation (e.g. aac1.ab30.123b).', max_length=32)),
                ('interface', models.CharField(help_text='Interface the ARP entry was learned on.', max_length=64)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
            ],
            options={
                'verbose_name': 'ARP Entry',
                'verbose_name_plural': 'ARP Entries',
                'ordering': ['device', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='BgpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrf', models.CharField(default='default', help_text='VRF this session belongs to.', max_length=64)),
                ('peer_ip', models.GenericIPAddressField(help_text='BGP peer IP address.', protocol='IPv4')),
                ('peer_asn', models.PositiveIntegerField(help_text='BGP peer AS number.')),
                ('peer_state', models.CharField(choices=[('Established', 'Established'), ('Active', 'Active'), ('Idle', 'Idle'), ('Connect', 'Connect'), ('OpenSent', 'OpenSent'), ('OpenConfirm', 'OpenConfirm'), ('Unknown', 'Unknown')], default='Unknown', help_text='Current BGP session state.', max_length=16)),
                ('prefixes_received', models.PositiveIntegerField(default=0, help_text='Number of prefixes received from this peer.')),
                ('prefixes_accepted', models.PositiveIntegerField(default=0, help_text='Number of prefixes accepted from this peer.')),
                ('updown_time', models.FloatField(blank=True, help_text='Raw upDownTime value from EOS BGP summary (EOS internal clock at last state change).', null=True)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
            ],
            options={
                'verbose_name': 'BGP Session',
                'verbose_name_plural': 'BGP Sessions',
                'ordering': ['device', 'vrf', 'peer_ip'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', help_text='Human-readable hostname of the device (optional).', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 address used to connect to the device.', protocol='IPv4', unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Optional free-text description of the device.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='PollingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this task.', max_length=100)),
                ('task_type', models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP'), ('lldp', 'LLDP')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this task last ran.', null=True)),
                ('last_success', models.BooleanField(blank=True, help_text='Whether the last run completed without errors.', null=True)),
            ],
            options={
                'verbose_name': 'Polling Task',
                'verbose_name_plural': 'Polling Tasks',
                'ordering': ['task_type'],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Job ID of the collection run.', max_length=64)),
                ('check_type', models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP'), ('lldp', 'LLDP')], help_text='Which data was collected in this check.', max_length=16)),
                ('started_at', models.DateTimeField(help_text='When this check started.')),
                ('duration_ms', models.PositiveIntegerField(help_text='How long the check took, in milliseconds.')),
                ('success', models.BooleanField(default=True, help_text='Whether the check completed without errors.')),
            ],
            options={
                'verbose_name': 'Poll Result',
                'verbose_name_plural': 'Poll Results',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BgpSessionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('vrf', models.CharField(default='default', help_text='VRF this session belongs to.', max_length=64)),
                ('peer_ip', models.GenericIPAddressField(help_text='BGP peer IP address.', protocol='IPv4')),
                ('peer_asn', models.PositiveIntegerField(help_text='BGP peer AS number.')),
                ('peer_state', models.CharField(choices=[('Established', 'Established'), ('Active', 'Active'), ('Idle', 'Idle'), ('Connect', 'Connect'), ('OpenSent', 'OpenSent'), ('OpenConfirm', 'OpenConfirm'), ('Unknown', 'Unknown')], default='Unknown', help_text='Current BGP session state.', max_length=16)),
                ('prefixes_received', models.PositiveIntegerField(default=0, help_text='Number of prefixes received from this peer.')),
                ('prefixes_accepted', models.PositiveIntegerField(default=0, help_text='Number of prefixes accepted from this peer.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.bgpsession')),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this BGP session was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='device',
            field=models.ForeignKey(help_text='Device this BGP session was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions', to='netorb.device'),
        ),
        migrations.CreateModel(
            name='ArpEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the ARP entry.', protocol='IPv4')),
                ('mac_address', models.CharField(help_text='MAC address in EOS dot-notation (e.g. aac1.ab30.123b).', max_length=32)),
                ('interface', models.CharField(help_text='Interface the ARP entry was learned on.', max_length=64)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.arpentry')),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this ARP entry was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='arpentry',
            name='device',
            field=models.ForeignKey(help_text='Device this ARP entry was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='netorb.device'),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Interface name as reported by the device (e.g. Ethernet1).', max_length=255)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', help_text='Operational status of the interface.', max_length=16)),
                ('primary_ip', models.CharField(blank=True, default='', help_text='Primary IPv4 address in CIDR notation (e.g. 10.0.0.1/24).', max_length=43)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this interface belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='netorb.device')),
            ],
            options={
                'verbose_name': 'Interface',
                'verbose_name_plural': 'Interfaces',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(help_text='Interface name as reported by the device (e.g. Ethernet1).', max_length=255)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', help_text='Operational status of the interface.', max_length=16)),
                ('primary_ip', models.CharField(blank=True, default='', help_text='Primary IPv4 address in CIDR notation (e.g. 10.0.0.1/24).', max_length=43)),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this interface belongs to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.interface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPv4Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', netfields.fields.CidrAddressField(help_text='Destination prefix in CIDR notation (e.g. 10.0.0.0/24).', max_length=43)),
                ('next_hops', models.JSONField(blank=True, default=list, help_text='List of next-hop objects, e.g. [{"nexthop": "10.0.0.1", "interface": "Ethernet1"}].')),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this route was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='ipv4_routes', to='netorb.device')),
            ],
            options={
                'verbose_name': 'IPv4 Route',
                'verbose_name_plural': 'IPv4 Routes',
                'ordering': ['device', 'prefix'],
            },
        ),
        migrations.CreateModel(
            name='IPv4RouteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('prefix', netfields.fields.CidrAddressField(help_text='Destination prefix in CIDR notation (e.g. 10.0.0.0/24).', max_length=43)),
                ('next_hops', models.JSONField(blank=True, default=list, help_text='List of next-hop objects, e.g. [{"nexthop": "10.0.0.1", "interface": "Ethernet1"}].')),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this route was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.ipv4route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LldpNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_port', models.CharField(help_text='Local interface name (e.g. Ethernet1).', max_length=255)),
                ('neighbor_device', models.CharField(help_text='Remote device name reported by LLDP.', max_length=255)),
                ('neighbor_port', models.CharField(help_text='Remote port name reported by LLDP.', max_length=255)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this LLDP neighbor was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='lldp_neighbors', to='netorb.device')),
            ],
            options={
                'verbose_name': 'LLDP Neighbor',
                'verbose_name_plural': 'LLDP Neighbors',
                'ordering': ['device', 'local_port'],
            },
        ),
        migrations.CreateModel(
            name='LldpNeighborEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('local_port', models.CharField(help_text='Local interface name (e.g. Ethernet1).', max_length=255)),
                ('neighbor_device', models.CharField(help_text='Remote device name reported by LLDP.', max_length=255)),
                ('neighbor_port', models.CharField(help_text='Remote port name reported by LLDP.', max_length=255)),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this LLDP neighbor was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.lldpneighbor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='django-q2 task ID that produced this entry.', max_length=64)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, help_text='Device being polled when this entry was emitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to='netorb.device')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(fields=('device', 'vrf', 'peer_ip'), name='unique_device_vrf_peer'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."vrf"); RETURN NULL;', hash='9cbd017d04a2ed5f6d08064a1972a917d1cde59a', operation='INSERT', pgid='pgtrigger_insert_insert_5752f', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."peer_asn" IS DISTINCT FROM (NEW."peer_asn") OR OLD."peer_ip" IS DISTINCT FROM (NEW."peer_ip") OR OLD."peer_state" IS DISTINCT FROM (NEW."peer_state") OR OLD."prefixes_accepted" IS DISTINCT FROM (NEW."prefixes_accepted") OR OLD."prefixes_received" IS DISTINCT FROM (NEW."prefixes_received") OR OLD."vrf" IS DISTINCT FROM (NEW."vrf"))', func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."vrf"); RETURN NULL;', hash='e8d40431839c4c5cfe92c6656d09e0e668ff3e6f', operation='UPDATE', pgid='pgtrigger_update_update_0d2dd', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (OLD."device_id", OLD."id", OLD."peer_asn", OLD."peer_ip", OLD."peer_state", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefixes_accepted", OLD."prefixes_received", OLD."vrf"); RETURN NULL;', hash='1f722b77e136cb0602fa43ba9de0912c5545c878', operation='DELETE', pgid='pgtrigger_delete_delete_f8280', table='netorb_bgpsession', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='arpentry',
            constraint=models.UniqueConstraint(fields=('device', 'ip_address'), name='unique_device_arp_ip'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='a4e75bb8393433d54d358d00e46dde07b5c7aa61', operation='INSERT', pgid='pgtrigger_insert_insert_3bad9', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."interface" IS DISTINCT FROM (NEW."interface") OR OLD."ip_address" IS DISTINCT FROM (NEW."ip_address") OR OLD."mac_address" IS DISTINCT FROM (NEW."mac_address"))', func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='5b587782e6c6f7723c799b8a0f31227fa4bbe28e', operation='UPDATE', pgid='pgtrigger_update_update_f594f', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."device_id", OLD."id", OLD."interface", OLD."ip_address", OLD."mac_address", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='224367e49adafb2b4302166ca1b83ee32bb8b4a5', operation='DELETE', pgid='pgtrigger_delete_delete_0f44f', table='netorb_arpentry', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_interface'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."primary_ip"); RETURN NULL;', hash='823ba8f67054ce5223ff2899c6f240adf8574385', operation='INSERT', pgid='pgtrigger_insert_insert_54b1b', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."oper_status" IS DISTINCT FROM (NEW."oper_status") OR OLD."primary_ip" IS DISTINCT FROM (NEW."primary_ip"))', func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."primary_ip"); RETURN NULL;', hash='f61f92ab994c32aa507662b86fe030dbf20c4c4d', operation='UPDATE', pgid='pgtrigger_update_update_4398f', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (OLD."device_id", OLD."id", OLD."name", OLD."oper_status", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."primary_ip"); RETURN NULL;', hash='4313e2b095ea11d5d5692587e99c55df7f26fe10', operation='DELETE', pgid='pgtrigger_delete_delete_23496', table='netorb_interface', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='ipv4route',
            constraint=models.UniqueConstraint(fields=('device', 'prefix'), name='unique_device_prefix'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (NEW."device_id", NEW."id", NEW."next_hops", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefix"); RETURN NULL;', hash='72874eb80cec2870b8b099d0895fbf668690b0c2', operation='INSERT', pgid='pgtrigger_insert_insert_b1b71', table='netorb_ipv4route', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."next_hops" IS DISTINCT FROM (NEW."next_hops") OR OLD."prefix" IS DISTINCT FROM (NEW."prefix"))', func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (NEW."device_id", NEW."id", NEW."next_hops", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefix"); RETURN NULL;', hash='66d39e407e269ac9e59e9f5ce5a840bff4e27c83', operation='UPDATE', pgid='pgtrigger_update_update_bc3b4', table='netorb_ipv4route', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (OLD."device_id", OLD."id", OLD."next_hops", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefix"); RETURN NULL;', hash='d60c105004d6a6cacec22d872d15c036ab95aaa6', operation='DELETE', pgid='pgtrigger_delete_delete_7b8f8', table='netorb_ipv4route', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='lldpneighbor',
            constraint=models.UniqueConstraint(fields=('device', 'local_port', 'neighbor_device', 'neighbor_port'), name='unique_device_lldp_neighbor'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."local_port", NEW."neighbor_device", NEW."neighbor_port", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='b1183b2f150e80b9c8d1d5723fdf951656e27f1c', operation='INSERT', pgid='pgtrigger_insert_insert_d03e5', table='netorb_lldpneighbor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."local_port" IS DISTINCT FROM (NEW."local_port") OR OLD."neighbor_device" IS DISTINCT FROM (NEW."neighbor_device") OR OLD."neighbor_port" IS DISTINCT FROM (NEW."neighbor_port"))', func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."local_port", NEW."neighbor_device", NEW."neighbor_port", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='155258ebbf5be323eaa6baa15028ba9cb02384eb', operation='UPDATE', pgid='pgtrigger_update_update_b1d31', table='netorb_lldpneighbor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."device_id", OLD."id", OLD."local_port", OLD."neighbor_device", OLD."neighbor_port", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='5dc23fbfb808d90e91c53b25cb01a99cb03a468e', operation='DELETE', pgid='pgtrigger_delete_delete_9c420', table='netorb_lldpneighbor', when='AFTER')),
        ),
    ]
