# Generated by Django 5.2.12 on 2026-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0003_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional free-text description of the device.', max_length=255),
        ),
    ]
