# Generated by Django 5.2.12 on 2026-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0004_device_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingschedule',
            options={'ordering': ['task_type'], 'verbose_name': 'Polling Schedule', 'verbose_name_plural': 'Polling Schedules'},
        ),
        migrations.RemoveConstraint(
            model_name='pollingschedule',
            name='unique_device_task_type',
        ),
        migrations.RemoveField(
            model_name='pollingschedule',
            name='device',
        ),
        migrations.AlterField(
            model_name='pollingschedule',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=5, help_text='How often to poll all devices, in minutes.'),
        ),
        migrations.AlterField(
            model_name='pollingschedule',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('all', 'All')], default='all', help_text='Which data to collect on each run (applies to all devices).', max_length=16, unique=True),
        ),
    ]
