# Generated by Django 5.2.12 on 2026-03-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0005_alter_pollingschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Job ID of the collection run.', max_length=64)),
                ('check_type', models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes')], help_text='Which data was collected in this check.', max_length=16)),
                ('started_at', models.DateTimeField(help_text='When this check started.')),
                ('duration_ms', models.PositiveIntegerField(help_text='How long the check took, in milliseconds.')),
                ('success', models.BooleanField(default=True, help_text='Whether the check completed without errors.')),
                ('device', models.ForeignKey(help_text='Device that was polled.', on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='netorb.device')),
            ],
            options={
                'verbose_name': 'Poll Result',
                'verbose_name_plural': 'Poll Results',
                'ordering': ['-started_at'],
            },
        ),
    ]
