# Generated by Django 5.2.12 on 2026-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0006_pollresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this task.', max_length=100)),
                ('task_type', models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('all', 'All')], default='all', help_text='Which data to collect when this task runs.', max_length=16, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this task last ran.', null=True)),
                ('last_success', models.BooleanField(blank=True, help_text='Whether the last run completed without errors.', null=True)),
            ],
            options={
                'verbose_name': 'Polling Task',
                'verbose_name_plural': 'Polling Tasks',
                'ordering': ['task_type'],
            },
        ),
        migrations.DeleteModel(
            name='PollingSchedule',
        ),
    ]
