# Generated by Django 5.2.12 on 2026-03-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0007_pollingtask_delete_pollingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingtask',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True),
        ),
    ]
