# Generated by Django 5.2.12 on 2026-03-15 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0008_alter_pollingtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingtask',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp', 'BGP')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='check_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp', 'BGP')], help_text='Which data was collected in this check.', max_length=16),
        ),
        migrations.CreateModel(
            name='BgpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrf', models.CharField(default='default', help_text='VRF this session belongs to.', max_length=64)),
                ('peer_ip', models.GenericIPAddressField(help_text='BGP peer IP address.', protocol='IPv4')),
                ('peer_asn', models.PositiveIntegerField(help_text='BGP peer AS number.')),
                ('peer_state', models.CharField(choices=[('Established', 'Established'), ('Active', 'Active'), ('Idle', 'Idle'), ('Connect', 'Connect'), ('OpenSent', 'OpenSent'), ('OpenConfirm', 'OpenConfirm'), ('Unknown', 'Unknown')], default='Unknown', help_text='Current BGP session state.', max_length=16)),
                ('prefixes_received', models.PositiveIntegerField(default=0, help_text='Number of prefixes received from this peer.')),
                ('prefixes_accepted', models.PositiveIntegerField(default=0, help_text='Number of prefixes accepted from this peer.')),
                ('updown_time', models.DateTimeField(blank=True, help_text='When the session last changed state.', null=True)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this BGP session was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions', to='netorb.device')),
            ],
            options={
                'verbose_name': 'BGP Session',
                'verbose_name_plural': 'BGP Sessions',
                'ordering': ['device', 'vrf', 'peer_ip'],
                'constraints': [models.UniqueConstraint(fields=('device', 'vrf', 'peer_ip'), name='unique_device_vrf_peer')],
            },
        ),
    ]
