# Generated by Django 5.2.12 on 2026-03-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0009_alter_pollingtask_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingtask',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='check_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions')], help_text='Which data was collected in this check.', max_length=16),
        ),
    ]
