# Generated by Django 5.2.12 on 2026-03-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0010_alter_pollingtask_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingtask',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='check_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP')], help_text='Which data was collected in this check.', max_length=16),
        ),
        migrations.CreateModel(
            name='ArpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the ARP entry.', protocol='IPv4')),
                ('mac_address', models.CharField(help_text='MAC address in EOS dot-notation (e.g. aac1.ab30.123b).', max_length=32)),
                ('interface', models.CharField(help_text='Interface the ARP entry was learned on.', max_length=64)),
                ('age', models.PositiveIntegerField(help_text='Age of the ARP entry in seconds.')),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this ARP entry was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='netorb.device')),
            ],
            options={
                'verbose_name': 'ARP Entry',
                'verbose_name_plural': 'ARP Entries',
                'ordering': ['device', 'ip_address'],
                'constraints': [models.UniqueConstraint(fields=('device', 'ip_address'), name='unique_device_arp_ip')],
            },
        ),
    ]
