# Generated by Django 5.2.12 on 2026-03-15 08:22

import django.contrib.postgres.fields
import django.db.models.deletion
import netfields.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0014_delete_nexthop'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the ARP entry.', protocol='IPv4')),
                ('mac_address', models.CharField(help_text='MAC address in EOS dot-notation (e.g. aac1.ab30.123b).', max_length=32)),
                ('interface', models.CharField(help_text='Interface the ARP entry was learned on.', max_length=64)),
                ('age', models.PositiveIntegerField(help_text='Age of the ARP entry in seconds.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BgpSessionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('vrf', models.CharField(default='default', help_text='VRF this session belongs to.', max_length=64)),
                ('peer_ip', models.GenericIPAddressField(help_text='BGP peer IP address.', protocol='IPv4')),
                ('peer_asn', models.PositiveIntegerField(help_text='BGP peer AS number.')),
                ('peer_state', models.CharField(choices=[('Established', 'Established'), ('Active', 'Active'), ('Idle', 'Idle'), ('Connect', 'Connect'), ('OpenSent', 'OpenSent'), ('OpenConfirm', 'OpenConfirm'), ('Unknown', 'Unknown')], default='Unknown', help_text='Current BGP session state.', max_length=16)),
                ('prefixes_received', models.PositiveIntegerField(default=0, help_text='Number of prefixes received from this peer.')),
                ('prefixes_accepted', models.PositiveIntegerField(default=0, help_text='Number of prefixes accepted from this peer.')),
                ('updown_time', models.DateTimeField(blank=True, help_text='When the session last changed state.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterfaceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(help_text='Interface name as reported by the device (e.g. Ethernet1).', max_length=255)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', help_text='Operational status of the interface.', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPv4RouteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('prefix', netfields.fields.CidrAddressField(help_text='Destination prefix in CIDR notation (e.g. 10.0.0.0/24).', max_length=43)),
                ('next_hops', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(protocol='IPv4'), blank=True, default=list, help_text='List of next-hop IPv4 addresses (empty for directly connected routes).', size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("age", "device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."age", NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='0056d53b45004f220febc72e9841447703594f64', operation='INSERT', pgid='pgtrigger_insert_insert_3bad9', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."age" IS DISTINCT FROM (NEW."age") OR OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."interface" IS DISTINCT FROM (NEW."interface") OR OLD."ip_address" IS DISTINCT FROM (NEW."ip_address") OR OLD."mac_address" IS DISTINCT FROM (NEW."mac_address"))', func='INSERT INTO "netorb_arpentryevent" ("age", "device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."age", NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='aec813e8e363b8a57fb6694c1823ec403298138a', operation='UPDATE', pgid='pgtrigger_update_update_f594f', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("age", "device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."age", OLD."device_id", OLD."id", OLD."interface", OLD."ip_address", OLD."mac_address", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='a09ed47ac64f9ac8a035bc07d3acbb4dc5eab62c', operation='DELETE', pgid='pgtrigger_delete_delete_0f44f', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "updown_time", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."updown_time", NEW."vrf"); RETURN NULL;', hash='a363250e3dc5e2b4d3a78f1ea22357ce66e5e3de', operation='INSERT', pgid='pgtrigger_insert_insert_5752f', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."peer_asn" IS DISTINCT FROM (NEW."peer_asn") OR OLD."peer_ip" IS DISTINCT FROM (NEW."peer_ip") OR OLD."peer_state" IS DISTINCT FROM (NEW."peer_state") OR OLD."prefixes_accepted" IS DISTINCT FROM (NEW."prefixes_accepted") OR OLD."prefixes_received" IS DISTINCT FROM (NEW."prefixes_received") OR OLD."updown_time" IS DISTINCT FROM (NEW."updown_time") OR OLD."vrf" IS DISTINCT FROM (NEW."vrf"))', func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "updown_time", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."updown_time", NEW."vrf"); RETURN NULL;', hash='9f8387b24d9e37b7bf6b7e4c2eee70561b30a73e', operation='UPDATE', pgid='pgtrigger_update_update_0d2dd', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "updown_time", "vrf") VALUES (OLD."device_id", OLD."id", OLD."peer_asn", OLD."peer_ip", OLD."peer_state", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefixes_accepted", OLD."prefixes_received", OLD."updown_time", OLD."vrf"); RETURN NULL;', hash='b6a35b12978f80eff7863842faf2756e3d68ebcc', operation='DELETE', pgid='pgtrigger_delete_delete_f8280', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='7b533aac44caa296c81fb120b648cda0334d46cf', operation='INSERT', pgid='pgtrigger_insert_insert_54b1b', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."oper_status" IS DISTINCT FROM (NEW."oper_status"))', func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='4b8e922b47eb807c53ba7ea3e5bb07278c5d9fa6', operation='UPDATE', pgid='pgtrigger_update_update_4398f', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."device_id", OLD."id", OLD."name", OLD."oper_status", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='831391974ad3c3c7f0e3f6002aa7e878489142c1', operation='DELETE', pgid='pgtrigger_delete_delete_23496', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (NEW."device_id", NEW."id", NEW."next_hops", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefix"); RETURN NULL;', hash='72874eb80cec2870b8b099d0895fbf668690b0c2', operation='INSERT', pgid='pgtrigger_insert_insert_b1b71', table='netorb_ipv4route', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."next_hops" IS DISTINCT FROM (NEW."next_hops") OR OLD."prefix" IS DISTINCT FROM (NEW."prefix"))', func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (NEW."device_id", NEW."id", NEW."next_hops", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefix"); RETURN NULL;', hash='66d39e407e269ac9e59e9f5ce5a840bff4e27c83', operation='UPDATE', pgid='pgtrigger_update_update_bc3b4', table='netorb_ipv4route', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ipv4route',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_ipv4routeevent" ("device_id", "id", "next_hops", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefix") VALUES (OLD."device_id", OLD."id", OLD."next_hops", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefix"); RETURN NULL;', hash='d60c105004d6a6cacec22d872d15c036ab95aaa6', operation='DELETE', pgid='pgtrigger_delete_delete_7b8f8', table='netorb_ipv4route', when='AFTER')),
        ),
        migrations.AddField(
            model_name='arpentryevent',
            name='device',
            field=models.ForeignKey(db_constraint=False, help_text='Device this ARP entry was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device'),
        ),
        migrations.AddField(
            model_name='arpentryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='arpentryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.arpentry'),
        ),
        migrations.AddField(
            model_name='bgpsessionevent',
            name='device',
            field=models.ForeignKey(db_constraint=False, help_text='Device this BGP session was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device'),
        ),
        migrations.AddField(
            model_name='bgpsessionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='bgpsessionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.bgpsession'),
        ),
        migrations.AddField(
            model_name='interfaceevent',
            name='device',
            field=models.ForeignKey(db_constraint=False, help_text='Device this interface belongs to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device'),
        ),
        migrations.AddField(
            model_name='interfaceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='interfaceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.interface'),
        ),
        migrations.AddField(
            model_name='ipv4routeevent',
            name='device',
            field=models.ForeignKey(db_constraint=False, help_text='Device this route was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device'),
        ),
        migrations.AddField(
            model_name='ipv4routeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='ipv4routeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.ipv4route'),
        ),
    ]
