# Generated by Django 5.2.12 on 2026-03-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0016_device_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['ip_address'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
