# Generated by Django 5.2.12 on 2026-03-15 17:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0017_alter_device_options'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='interface',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='interface',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='interface',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='interface',
            name='primary_ip',
            field=models.CharField(blank=True, default='', help_text='Primary IPv4 address in CIDR notation (e.g. 10.0.0.1/24).', max_length=43),
        ),
        migrations.AddField(
            model_name='interfaceevent',
            name='primary_ip',
            field=models.CharField(blank=True, default='', help_text='Primary IPv4 address in CIDR notation (e.g. 10.0.0.1/24).', max_length=43),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."primary_ip"); RETURN NULL;', hash='823ba8f67054ce5223ff2899c6f240adf8574385', operation='INSERT', pgid='pgtrigger_insert_insert_54b1b', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."oper_status" IS DISTINCT FROM (NEW."oper_status") OR OLD."primary_ip" IS DISTINCT FROM (NEW."primary_ip"))', func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (NEW."device_id", NEW."id", NEW."name", NEW."oper_status", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."primary_ip"); RETURN NULL;', hash='f61f92ab994c32aa507662b86fe030dbf20c4c4d', operation='UPDATE', pgid='pgtrigger_update_update_4398f', table='netorb_interface', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='interface',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_interfaceevent" ("device_id", "id", "name", "oper_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_ip") VALUES (OLD."device_id", OLD."id", OLD."name", OLD."oper_status", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."primary_ip"); RETURN NULL;', hash='4313e2b095ea11d5d5692587e99c55df7f26fe10', operation='DELETE', pgid='pgtrigger_delete_delete_23496', table='netorb_interface', when='AFTER')),
        ),
    ]
