# Generated by Django 5.2.12 on 2026-03-15 21:30

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0019_next_hops_json'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='arpentry',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='arpentry',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='arpentry',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='arpentryevent',
            name='age',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='a4e75bb8393433d54d358d00e46dde07b5c7aa61', operation='INSERT', pgid='pgtrigger_insert_insert_3bad9', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."interface" IS DISTINCT FROM (NEW."interface") OR OLD."ip_address" IS DISTINCT FROM (NEW."ip_address") OR OLD."mac_address" IS DISTINCT FROM (NEW."mac_address"))', func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."interface", NEW."ip_address", NEW."mac_address", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='5b587782e6c6f7723c799b8a0f31227fa4bbe28e', operation='UPDATE', pgid='pgtrigger_update_update_f594f', table='netorb_arpentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='arpentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_arpentryevent" ("device_id", "id", "interface", "ip_address", "mac_address", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."device_id", OLD."id", OLD."interface", OLD."ip_address", OLD."mac_address", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='224367e49adafb2b4302166ca1b83ee32bb8b4a5', operation='DELETE', pgid='pgtrigger_delete_delete_0f44f', table='netorb_arpentry', when='AFTER')),
        ),
    ]
