# Generated by Django 5.2.12 on 2026-03-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0020_remove_arpentry_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device that was polled (null for batch summary rows).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='netorb.device'),
        ),
    ]
