# Generated by Django 5.2.12 on 2026-03-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0021_alter_pollresult_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresult',
            name='device',
        ),
    ]
