# Generated by Django 5.2.12 on 2026-03-15 22:25

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0022_remove_pollresult_device'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingtask',
            name='task_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP'), ('lldp', 'LLDP')], default='interfaces', help_text='Which data to collect when this task runs.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='check_type',
            field=models.CharField(choices=[('interfaces', 'Interfaces'), ('routes', 'Routes'), ('bgp_sessions', 'BGP Sessions'), ('arp', 'ARP'), ('lldp', 'LLDP')], help_text='Which data was collected in this check.', max_length=16),
        ),
        migrations.CreateModel(
            name='LldpNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_port', models.CharField(help_text='Local interface name (e.g. Ethernet1).', max_length=255)),
                ('neighbor_device', models.CharField(help_text='Remote device name reported by LLDP.', max_length=255)),
                ('neighbor_port', models.CharField(help_text='Remote port name reported by LLDP.', max_length=255)),
                ('collected_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last data collection.')),
                ('device', models.ForeignKey(help_text='Device this LLDP neighbor was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='lldp_neighbors', to='netorb.device')),
            ],
            options={
                'verbose_name': 'LLDP Neighbor',
                'verbose_name_plural': 'LLDP Neighbors',
                'ordering': ['device', 'local_port'],
            },
        ),
        migrations.CreateModel(
            name='LldpNeighborEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('local_port', models.CharField(help_text='Local interface name (e.g. Ethernet1).', max_length=255)),
                ('neighbor_device', models.CharField(help_text='Remote device name reported by LLDP.', max_length=255)),
                ('neighbor_port', models.CharField(help_text='Remote port name reported by LLDP.', max_length=255)),
                ('device', models.ForeignKey(db_constraint=False, help_text='Device this LLDP neighbor was collected from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='netorb.device')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='netorb.lldpneighbor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='lldpneighbor',
            constraint=models.UniqueConstraint(fields=('device', 'local_port', 'neighbor_device', 'neighbor_port'), name='unique_device_lldp_neighbor'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."local_port", NEW."neighbor_device", NEW."neighbor_port", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='b1183b2f150e80b9c8d1d5723fdf951656e27f1c', operation='INSERT', pgid='pgtrigger_insert_insert_d03e5', table='netorb_lldpneighbor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."local_port" IS DISTINCT FROM (NEW."local_port") OR OLD."neighbor_device" IS DISTINCT FROM (NEW."neighbor_device") OR OLD."neighbor_port" IS DISTINCT FROM (NEW."neighbor_port"))', func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."device_id", NEW."id", NEW."local_port", NEW."neighbor_device", NEW."neighbor_port", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='155258ebbf5be323eaa6baa15028ba9cb02384eb', operation='UPDATE', pgid='pgtrigger_update_update_b1d31', table='netorb_lldpneighbor', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lldpneighbor',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_lldpneighborevent" ("device_id", "id", "local_port", "neighbor_device", "neighbor_port", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."device_id", OLD."id", OLD."local_port", OLD."neighbor_device", OLD."neighbor_port", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='5dc23fbfb808d90e91c53b25cb01a99cb03a468e', operation='DELETE', pgid='pgtrigger_delete_delete_9c420', table='netorb_lldpneighbor', when='AFTER')),
        ),
    ]
