# Generated by Django 5.2.12 on 2026-03-17 21:32

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0023_alter_pollingtask_task_type_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='arpentry',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='updown_time',
        ),
        migrations.RunSQL(
            "ALTER TABLE netorb_bgpsessionevent DROP COLUMN IF EXISTS updown_time",
            migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='time_of_last_change',
            field=models.DateTimeField(blank=True, help_text='When the session last changed state, calculated from device-reported uptime.', null=True),
        ),
        migrations.AddField(
            model_name='bgpsessionevent',
            name='time_of_last_change',
            field=models.DateTimeField(blank=True, help_text='When the session last changed state, calculated from device-reported uptime.', null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "time_of_last_change", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."time_of_last_change", NEW."vrf"); RETURN NULL;', hash='13e95c781d749199de0bb6db1ad1d17bb8e5db56', operation='INSERT', pgid='pgtrigger_insert_insert_5752f', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."peer_asn" IS DISTINCT FROM (NEW."peer_asn") OR OLD."peer_ip" IS DISTINCT FROM (NEW."peer_ip") OR OLD."peer_state" IS DISTINCT FROM (NEW."peer_state") OR OLD."prefixes_accepted" IS DISTINCT FROM (NEW."prefixes_accepted") OR OLD."prefixes_received" IS DISTINCT FROM (NEW."prefixes_received") OR OLD."time_of_last_change" IS DISTINCT FROM (NEW."time_of_last_change") OR OLD."vrf" IS DISTINCT FROM (NEW."vrf"))', func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "time_of_last_change", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."time_of_last_change", NEW."vrf"); RETURN NULL;', hash='54ba31ab9611b9a19ae69b67103d724ee6aa62d1', operation='UPDATE', pgid='pgtrigger_update_update_0d2dd', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "time_of_last_change", "vrf") VALUES (OLD."device_id", OLD."id", OLD."peer_asn", OLD."peer_ip", OLD."peer_state", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefixes_accepted", OLD."prefixes_received", OLD."time_of_last_change", OLD."vrf"); RETURN NULL;', hash='eb2392fd0c97e95787bce3b5591ff25acbd46f4b', operation='DELETE', pgid='pgtrigger_delete_delete_f8280', table='netorb_bgpsession', when='AFTER')),
        ),
    ]
