# Generated by Django 5.2.12 on 2026-03-17 22:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0024_remove_bgpsession_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='bgpsession',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='time_of_last_change',
        ),
        migrations.RemoveField(
            model_name='bgpsessionevent',
            name='time_of_last_change',
        ),
        migrations.RunSQL(
            "ALTER TABLE netorb_bgpsessionevent DROP COLUMN IF EXISTS updown_time",
            migrations.RunSQL.noop,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."vrf"); RETURN NULL;', hash='9cbd017d04a2ed5f6d08064a1972a917d1cde59a', operation='INSERT', pgid='pgtrigger_insert_insert_5752f', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."peer_asn" IS DISTINCT FROM (NEW."peer_asn") OR OLD."peer_ip" IS DISTINCT FROM (NEW."peer_ip") OR OLD."peer_state" IS DISTINCT FROM (NEW."peer_state") OR OLD."prefixes_accepted" IS DISTINCT FROM (NEW."prefixes_accepted") OR OLD."prefixes_received" IS DISTINCT FROM (NEW."prefixes_received") OR OLD."vrf" IS DISTINCT FROM (NEW."vrf"))', func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (NEW."device_id", NEW."id", NEW."peer_asn", NEW."peer_ip", NEW."peer_state", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefixes_accepted", NEW."prefixes_received", NEW."vrf"); RETURN NULL;', hash='e8d40431839c4c5cfe92c6656d09e0e668ff3e6f', operation='UPDATE', pgid='pgtrigger_update_update_0d2dd', table='netorb_bgpsession', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bgpsession',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "netorb_bgpsessionevent" ("device_id", "id", "peer_asn", "peer_ip", "peer_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefixes_accepted", "prefixes_received", "vrf") VALUES (OLD."device_id", OLD."id", OLD."peer_asn", OLD."peer_ip", OLD."peer_state", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefixes_accepted", OLD."prefixes_received", OLD."vrf"); RETURN NULL;', hash='1f722b77e136cb0602fa43ba9de0912c5545c878', operation='DELETE', pgid='pgtrigger_delete_delete_f8280', table='netorb_bgpsession', when='AFTER')),
        ),
    ]
