# Generated by Django 5.2.12 on 2026-03-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netorb', '0025_remove_bgpsession_time_of_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='updown_time',
            field=models.FloatField(blank=True, help_text='Raw upDownTime value from EOS BGP summary (EOS internal clock at last state change).', null=True),
        ),
    ]
